<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/13JulAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
matrix1 = np.random.randint(1,20,(3,2))
matrix1

array([[12, 11],
       [14,  3],
       [15, 17]])

In [21]:
matrix2 = np.random.randint(1,20,(2,3))
matrix2

array([[14, 16, 15],
       [14,  8,  8]])

In [22]:
np.dot(matrix1,matrix2)

array([[322, 280, 268],
       [238, 248, 234],
       [448, 376, 361]])

In [23]:
print(matrix1)
print(np.matrix_transpose(matrix1))


[[12 11]
 [14  3]
 [15 17]]
[[12 14 15]
 [11  3 17]]


In [24]:
np.matmul(matrix1,matrix2)

array([[322, 280, 268],
       [238, 248, 234],
       [448, 376, 361]])

In [28]:
matrix1 @ matrix2

array([[322, 280, 268],
       [238, 248, 234],
       [448, 376, 361]])