<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/13JulAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
matrix1 = np.random.randint(1,20,(3,2))
matrix1

array([[12, 11],
       [14,  3],
       [15, 17]])

In [6]:
matrix2 = np.random.randint(1,20,(2,2))
matrix2

array([[ 8,  9],
       [ 3, 15]])

In [8]:
np.dot(matrix1,matrix2)

array([[129, 273],
       [121, 171],
       [171, 390]])

In [18]:
print(matrix1)
print(np.matrix_transpose(matrix1))


[[12 11]
 [14  3]
 [15 17]]
[[12 14 15]
 [11  3 17]]
