<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/13JUlNumpyLinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.random.seed(5)
np.random.randint(0 , 100 , (5))

array([99, 78, 61, 16, 73])

In [ ]:
matrix = np.random.randint(1 , 100 , (2 , 2))

In [ ]:
matrix, matrix.T

(array([[ 9, 63],
        [28, 31]]),
 array([[ 9, 28],
        [63, 31]]))

In [ ]:
matrix.shape

(2, 2)

In [ ]:
np.linalg.inv(matrix)

array([[-0.02087542,  0.04242424],
       [ 0.01885522, -0.00606061]])