<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/13JULExcercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
'''
Make a random 2D array containing temperatures of 5 days each day should contain 3 temperatures  ex: [ [ 1,55, 44],
				       [ 5,12, 64],
				       [ 5,12, 64],
				       [ 30,12, 64],
				       [ 15,22, 6]]

Then give me all hot degrees (>25)  all cold degrees (<10) and all normal degrees( 10 < xx < 25 )
'''

import numpy as np

temps = np.random.randint(0,50, size=(5,3))

print(temps)

[[48 40  6]
 [43 28  9]
 [ 7 45 19]
 [35 14 35]
 [21 15 19]]


In [6]:
# all hot degrees
print(temps[temps>25])

[48 40 43 28 45 35 35]


In [7]:
# all cold degrees
print(temps[temps<10])

[6 9 7]


In [8]:
# All normal degrees
print(temps[(temps>10) & (temps<25)])

[19 14 21 15 19]
