<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/13JULTemps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
'''
Make a random 2D array containing temperatures of 5 days each day should contain 3 temperatures  ex: [ [ 1,55, 44],
				       [ 5,12, 64],
				       [ 5,12, 64],
				       [ 30,12, 64],
				       [ 15,22, 6]]

Then give me all hot degrees (>25)  all cold degrees (<10) and all normal degrees( 10 < xx < 25 )
'''

import numpy as np

temps = np.random.randint(0,50,(5,3))

print(temps)

[[45 13  6]
 [ 8 49 43]
 [45  3  3]
 [43 46 42]
 [45 23 15]]


In [12]:
# all hot degrees
print(temps[temps>25])

[45 49 43 45 43 46 42 45]


In [13]:
# all cold degrees
print(temps[temps<10])

[6 8 3 3]


In [14]:
# All normal degrees
print(temps[(temps>10) & (temps<25)])

[13 23 15]
