<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/18JUL2025_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
Ai Session 17 - Friday Jul 18 2025 - Programming Python #8 - Libraries (pandas) # 1

Create a function takes a list array then replace each -ve number with zero

Make one implementation with loop and the other with numpy



'''
# this is the loop approch

def replaceNegative(arr):
  for i in range(len(arr)):
    if arr[i] <0:
      arr[i]=0
  return arr
arr=[1,0,1,40,-3,5,3,-3,2,6,-5]
print(replaceNegative(arr))

[1, 0, 1, 40, 0, 5, 3, 0, 2, 6, 0]


In [3]:
'''
Ai Session 17 - Friday Jul 18 2025 - Programming Python #8 - Libraries (pandas) # 1

Create a function takes a list array then replace each -ve number with zero

Make one implementation with loop and the other with numpy

'''
# this is the numpy approch
import numpy as np

def replaceNegative(arr):
  np.place(arr,arr<0,0)
  return arr
arr=np.array([1,0,1,40,-3,5,3,-3,2,6,-5])
print(replaceNegative(arr))




[ 1  0  1 40  0  5  3  0  2  6  0]


In [4]:
'''
Ai Session 17 - Friday Jul 18 2025 - Programming Python #8 - Libraries (pandas) # 1

Create a function takes a list array then replace each -ve number with zero

Make one implementation with loop and the other with numpy

'''
# this is the another numpy approch
import numpy as np

def replaceNegative(arr):
  np.where(arr<0,0,arr)
  return arr
arr=np.array([1,0,1,40,-3,5,3,-3,2,6,-5])
print(replaceNegative(arr))


[ 1  0  1 40 -3  5  3 -3  2  6 -5]


In [15]:
'''
Ai Session 17 - Friday Jul 18 2025 - Programming Python #8 - Libraries (pandas) # 1

Create a function takes a list array then replace each -ve number with zero

Make one implementation with loop and the other with numpy

'''
# this is the another numpy approch
import numpy as np

def replaceNegative(arr):
  arr[arr<0]=0
  return arr
np.random.seed(0)
arr=np.random.randint(-10,10,10)
print(replaceNegative(arr))


[2 5 0 0 0 0 0 9 8 0]
