<a href="https://colab.research.google.com/github/ahmedebeed555/Python/blob/main/18Jul2025Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
scores  = np.random.randint(0 , 100 , (10))
scores

array([82, 65, 86, 61, 95, 95, 67, 63,  4, 10])

In [ ]:
scores[scores <50]

array([ 4, 10])

In [ ]:
scores.size, scores.shape

(10, (10,))

In [ ]:
scores[scores < 50 ] += 10
scores

array([82, 65, 86, 61, 95, 95, 67, 63, 14, 20])

In [ ]:
scores[scores <50]

array([14, 20])

# Tempreture Example

In [ ]:
temps = np.random.randint(0 , 50 , (5 , 3))
temps

array([[19, 10, 44],
       [15, 18,  7],
       [16, 47, 19],
       [40, 44, 20],
       [27, 46, 45]])

In [ ]:
temps[temps < 10]

array([7])

In [ ]:
cold_days = temps[temps < 10 ]
cold_days

array([7])

In [ ]:
temps

array([[19, 10, 44],
       [15, 18,  7],
       [16, 47, 19],
       [40, 44, 20],
       [27, 46, 45]])

In [ ]:
temps > 25

array([[False, False,  True],
       [False, False, False],
       [False,  True, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [ ]:
hot_days = temps[temps > 25]
hot_days

array([44, 47, 40, 44, 27, 46, 45])

In [ ]:
normal_days = temps[(temps > 10) & (temps < 25) ]
normal_days

array([19, 15, 18, 16, 19, 20])

In [ ]:
(temps > 10) , (temps < 25)

(array([[ True, False,  True],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True,  True, False],
        [ True,  True,  True],
        [ True, False,  True],
        [False, False,  True],
        [False, False, False]]))

# Sales Data

In [ ]:
sales = np.random.randint(0 , 100000 , (10000000))
sales

array([81019, 86865, 96933, ...,   954, 84063, 58498])

In [ ]:
np.sum(sales)

np.int64(500120630059)

In [ ]:
np.mean(sales) , np.median(sales), np.std(sales) , np.var(sales)

(np.float64(50012.0630059),
 np.float64(50014.0),
 np.float64(28872.466339475555),
 np.float64(833619312.524149))

In [ ]:
np.max(sales), np.min(sales), np.average(sales)

(np.int64(99999), np.int64(0), np.float64(50012.0630059))

In [ ]:
nums = np.array([2 , 5 , 0])

In [ ]:
np.exp(nums)

array([  7.3890561, 148.4131591,   1.       ])

#Linear Algebra

In [ ]:
matrix1 = np.random.randint(1, 20 , (3 , 2))
matrix2 = np.random.randint(1, 20 , (2, 3))

In [ ]:
matrix1 , matrix2

(array([[ 5, 19],
        [ 5, 12],
        [ 9, 19]]),
 array([[12, 11,  9],
        [ 8,  8, 13]]))

In [ ]:
vec1 = np.random.randint(0 , 20  , (10))
vec2 = np.random.randint(0 , 20  , (10))

In [ ]:
vec1 , vec2

(array([19, 13, 10, 16, 18,  4,  5, 13, 12,  6]),
 array([ 7,  5,  3, 15, 16, 12,  1, 14,  0, 19]))

In [ ]:
np.dot(vec1 , vec2)

np.int64(1105)

In [ ]:
matrix1.shape , matrix2.shape

((3, 2), (2, 3))

In [ ]:
np.matmul(matrix1, matrix2)

array([[212, 207, 292],
       [156, 151, 201],
       [260, 251, 328]])

In [ ]:
matrix1 @ matrix2

array([[212, 207, 292],
       [156, 151, 201],
       [260, 251, 328]])